markdown: kramdown

page_gen:
- index_files: true
  data: 'translations'
  template: 'translation'
  name: 'code'
  dir: ''
- index_files: false
  data: 'guides'
  template: 'guides'
  name: 'id'
  dir: 'guides'
  
algolia:
  application_id: 0IPEUWCLRX
  index_name:     manager
  nodes_to_index: 'div.guide p,div.guide li,div.guide h3,div.guide h4,div.guide h5,div.guide h6'
  files_to_exclude:
  - guides/index.html
  settings:
    searchableAttributes:
    - unordered(hierarchy.lvl2)    
    - unordered(hierarchy.lvl1)
    - unordered(hierarchy.lvl0)
    - unordered(content)
    customRanking:
    - asc(rank)
    unretrievableAttributes: []
    attributesToHighlight:
    - content
    - hierarchy.lvl0
    - hierarchy.lvl1
    - hierarchy.lvl2
    highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">'
    highlightPostTag: '</span>'
    attributesToSnippet:
    - content:55
    - hierarchy.lvl0:10
    - hierarchy.lvl1:10
    - hierarchy.lvl2:10
    attributesForFaceting: []