markdown: kramdown

page_gen:
- index_files: true
  data: 'translations'
  template: 'translation'
  name: 'code'
  dir: ''
- index_files: false
  data: 'guides'
  template: 'guides'
  name: 'id'
  dir: 'guides'
  
algolia:
  application_id: 0IPEUWCLRX
  index_name:     manager
  nodes_to_index: 'div.guide p,div.guide li'
  files_to_exclude:
  - guides/index.html