markdown: kramdown
include: [ '_redirects' ]
page_gen:
- index_files: true
  data: 'translations'
  template: 'translation'
  name: 'code'
  dir: ''
- index_files: false
  data: 'guides'
  template: 'guides'
  name: 'id'
  dir: 'guides'
- index_files: false
  data: 'cloud_pricing'
  template: 'cloud_pricing'
  name: 'Code'
  dir: 'cloud/pricing'