markdown: kramdown
page_gen:
- index_files: true
  data: 'translations'
  template: 'translation'
  name: 'code'
  dir: ''
- index_files: false
  data: 'guides'
  template: 'guides'
  name: 'id'
  dir: 'guides'